### ISSUE TITLE
New kernel old mistakes...

### ISSUE THREAD

**Issue by QB4-dev** [SoMLabs/somlabs-linux-imx#1]
Hello SoMLabs
I would like to point out some design mistakes in your devicetree. This kernel will be useful only on VisionCB-STD boards, nowhere else without significant device-tree modifications.

Visionsom6ull board itself i not a MACHINE in Yocto meaning. It becomes linux machine after inserting it on carrier board in designed device(like for example VisionCB-STD)

SOM board and carrier board definitions should not be mixed, lets take a look on your devicetree:
https://github.com/SoMLabs/somlabs-debian-6ull-linux-imx/blob/imx_5.4.3_2.0.0/arch/arm/boot/dts/somlabs-visionsom-6ull.dts

* model
```
model = "SoMLabs VisionSOM-6ULL";
compatible = "fsl,imx6ull-14x14-evk", "fsl,imx6ull";
```
It is not `imx6ull-14x14-evk` board

* chosen 
```
chosen {
	stdout-path = &uart1;
};
```
This is carrier board specific - what if i want to use another uart port for console in my device?

* leds 
```
leds {
compatible = "gpio-leds";
...
```
Does visionsom6ull board have leds? I dont think so - carrier board specific

* USB  regulators
```
		reg_usb_otg1_vbus: regulator@2 
		reg_usb_otg2_vbus: regulator@3 
};
```
Again -  carrier board specific

* WiFi/BT module 
```
wlan_pwrseq: wlanpwrseq 
&usdhc1 {
brcmf: bcrmf@1 {
	brcmf: bcrmf@1 {
		reg = <1>;
		compatible = "brcm,bcm4329-fmac";
       };
};

```
WiFi/BT module is optional - shouldn't be mandatory. For example we are using usdhc1 controller as microSD host

and so on with Ethernet controller, LCD controller, Touchscreen.... everything is mixed.
If somebody will want to use this kernel will need to rewrite entire devicetree including SOM board description(and he must know all electrical connections on board).

Here is good tutorial how to keep separated Module and Carrierboard:
https://developer.toradex.com/device-tree-customization#iMX_6ULL_based_Modules

I am maintaining my own layer for somlabs boards, here are my devicetrees:
https://github.com/QB4-dev/meta-somlabs-bsp/tree/master/recipes-kernel/linux/device-tree

I think they should be included in kernel code in this form:

file | purpouse
-- | --
visionsom-6ull.dtsi | common definitions for visionsom6ull boards
visionsom-6ull-wifibt.dtsi | murata WiFi/BT module pinconfig
visionsom-6ull-nand.dtsi | module with NAND memory
visionsom-6ull-nand-wifi.dtsi | module with NAND memory  + WiFi/BT
visionsom-6ull-emmc.dtsi | module with EMMC memory
visionsom-6ull-emmc-wifi.dtsi | module with EMMC memory  + WiFi/BT
visionsom-6ull-sd.dtsi | module with SD card
visionsom-6ull-sd-wifi.dtsi | module with SD card+ WiFi/BT

In company where I work we created 3 different projects based on this Yocto setup where you need to create .dtsi file with device/carrier board description like here for VisionCB-STD:

https://github.com/QB4-dev/meta-somlabs-bsp/blob/master/recipes-kernel/linux/device-tree/somlabs-board-dts/visioncb-std.dtsi

and later just include used variant of `visionsom-6ull` board:
```
#include "visionsom-6ull-emmc-wifi.dtsi"
#include "visioncb-std.dtsi"

/ {
        model = "Somlabs VisionSOM6ULL emmc WiFi on VisionCB-STD";
        compatible = "somlabs,visionsom6ull","somlabs,visioncb-std","fsl,imx6ull";
};
```

It really makes life easier

Best regards

**Comment by kchojnowski** [comment]
Hi, thanks for pointing out this issue. I have finally found some time to rewrite the DT files in a modular way. The changes are in a separate branch (imx_5.4.3_2.0.0_modular_dt) and will be merged after some more testing.

**Comment by QB4-dev** [comment]
@kchojnowski very, very good job! 
Now somlabs kernel will be useful in real projects. I also see that You created new yocto layer https://github.com/SoMLabs/imx-meta-somlabs
Finally Yocto support looks as it should be!

If You want to support Yocto dunfell please merge my pull request to `somlabs-uboot-imx`
https://github.com/SoMLabs/somlabs-uboot-imx/pull/5

**Comment by kchojnowski** [comment]
@QB4-dev I have just merged the modular DT to the master branch - I guess we can close this issue.

In the next step I will add the support of these DTs to the new Yocto-layer.

**Comment by QB4-dev** [comment]
Yes. We can close this issue. Thanks for your efforts
