### ISSUE TITLE
Using extended bluetooth mgmt commands VisionSom 6ULL

### ISSUE THREAD

**Issue by primus192** [SoMLabs/somlabs-linux-imx#3]
Hi. I have got a problem when trying to set Minimum and maximum advertising intervals in bluez. 
Dev told me that my kernel may not support it. Can you have a look at it and tell me if it is kernel problem or can i somehow enable it while configuring kernel? I am using kernel from somlabs wiki:

git clone https://github.com/SoMLabs/somlabs-linux-imx.git linux-imx

Source:
https://github.com/bluez/bluez/issues/314#issuecomment-1064624060
May be relevant:
https://www.spinics.net/lists/linux-bluetooth/msg87661.html
https://patchwork.kernel.org/project/bluetooth/patch/20201029141832.Bluez.v5.6.Ia49df7ccded97ceb4ff1d1b0decc49d03d088a84@changeid/

**Comment by kchojnowski** [comment]
Hi, I have never used this feature so I may be wrong about it, however I suppose that the Extended Advertising Parameters Command (0x0054) should be listed in include/net/bluetooth/mgmt.h file. According to the official kernel sources it was added in version 5.11. Our newest kernel is 5.10.72, so I guess that the extended commands are not supported.

**Comment by primus192** [comment]
I see. Can i use newest original nxp kernel for this board?
